import type { Role } from "@/lib/auth";
import type { LayerCollection, LayerFeature } from "@/lib/layers-api";
import { GIS_REGISTRY, isVisibleToRole, type LayerRegistryEntry } from "@/lib/gis-registry";

// Static stand-in for the Go API's /api/layers + /api/login, so this frontend
// can run as a demo with no backend. Per-layer geometry is served from
// public/gis/ (generated by scripts/prepare-gis-data.mjs from the real
// Shetrunjay dataset); role filtering mirrors role_layer_permissions via
// each registry row's `visibility` field in lib/gis-registry.ts.

const AVAILABLE_LAYERS = GIS_REGISTRY.filter(
  (entry) => entry.status === "available" && entry.assetPath,
);

function pickAttrs(
  properties: GeoJSON.GeoJsonProperties,
  fields: string[] | undefined,
): Record<string, string | number | null> {
  const attrs: Record<string, string | number | null> = {};
  if (!fields || !properties) return attrs;
  for (const field of fields) {
    const value = properties[field];
    attrs[field] = typeof value === "string" || typeof value === "number" ? value : null;
  }
  return attrs;
}

async function loadLayer(entry: LayerRegistryEntry): Promise<LayerFeature[]> {
  const res = await fetch(`/${entry.assetPath}`);
  if (!res.ok) throw new Error(`Failed to load layer "${entry.id}": ${res.status} ${res.statusText}`);
  const collection = (await res.json()) as GeoJSON.FeatureCollection;

  // GeoJSON allows a null geometry (e.g. an unmapped/pending record) — a
  // handful of real features are null after coordinate rounding collapsed a
  // sliver to nothing. Drop them here so every downstream consumer (map
  // rendering, bounds fitting, the legend) can assume geometry is present.
  return collection.features
    .filter((feature): feature is GeoJSON.Feature & { geometry: GeoJSON.Geometry } => feature.geometry !== null)
    .map((feature) => ({
      ...feature,
      properties: {
        id: entry.numericId,
        name: entry.name,
        layerId: entry.id,
        group: entry.group,
        attrs: pickAttrs(feature.properties, entry.attributeFields),
      },
    })) as LayerFeature[];
}

export async function layersForRole(role: Role | null): Promise<LayerCollection> {
  const visible = AVAILABLE_LAYERS.filter((entry) => isVisibleToRole(entry, role));
  const featureSets = await Promise.all(visible.map(loadLayer));
  return {
    type: "FeatureCollection",
    features: featureSets.flat(),
  };
}

interface MockUser {
  username: string;
  password: string;
  role: Role;
}

// Same three mock accounts as infra/postgis-init/init.sql (password123 for all).
const MOCK_USERS: MockUser[] = [
  { username: "regular_user", password: "password123", role: "regular_user" },
  { username: "admin_user", password: "password123", role: "admin" },
  { username: "support_user", password: "password123", role: "support_team" },
];

function base64url(value: object): string {
  const base64 = btoa(JSON.stringify(value));
  return base64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

// There's no backend left to sign a real JWT, but lib/auth.ts only ever
// decodes claims client-side — it never verifies a signature — so an
// unsigned token with the same header/payload shape is enough to demo login.
export function mockLogin(username: string, password: string): string | null {
  const user = MOCK_USERS.find((u) => u.username === username && u.password === password);
  if (!user) return null;
  const header = base64url({ alg: "none", typ: "JWT" });
  const payload = base64url({ sub: user.username, role_name: user.role });
  return `${header}.${payload}.`;
}
